# create by github.com/niizam , edit by YarBurArt
from playwright.sync_api import ElementHandle
from playwright.sync_api import sync_playwright
from playwright._impl._api_types import TimeoutError


def run(playwright, message: str,
        chara_id: str = "3LnH7nShX-dOrtOpJ0MSBgkuuA2PFjZI4nSiJ997iSc") -> str:
    """
    :param playwright: to operate the virtual browser
    :param message: this text will be inserted into the chat box
    :return: text generated by character.ai on rei chat
    """
    # chara_id = "zb7I4U9OYfewmEgOWLBHScefPeELkm1J-_GZDjHLY1M" # q&a
    # chara_id = "3LnH7nShX-dOrtOpJ0MSBgkuuA2PFjZI4nSiJ997iSc" # rei 1
    # chara_id = "mWlPN3NU6GyyZKUiV93bfe_-LjIg4el7YY6BpUtpRlk" # rei 2
    context = playwright.firefox.launch(headless=True).new_context()
    page = context.new_page()
    page.goto('https://beta.character.ai/chat?char=' + chara_id)

    page.get_by_role("button", name="Accept").click()
    page.get_by_placeholder("Type a message").fill(message)
    page.get_by_placeholder("Type a message").press("Enter")

    page.wait_for_selector('.swiper-button-next').is_visible()
    div: ElementHandle = page.query_selector('div.msg.char-msg')
    output_text: str = div.inner_text()

    context.close()
    return output_text


if __name__ == '__main__':
    message = input("Your message: ")
    try:
        with sync_playwright() as playwright:
            print(run(playwright, message))
    except TimeoutError:
        print("error: server timed out")
